### ISSUE TITLE
What is the purpose of bpf program template and can you help?

### ISSUE THREAD

**Issue by johhnsmmith198** [mvines/solana-bpf-program-template#13]
I am trying to find information about bpf compilation because I am having a compilation problem when adding a rust library to the example-helloworld solana program.
Aren't all solana program compiled into bpf? what is this template providing?

It seems solana is unable to compile the c bindings of the rust library I added. I was wondering if you can help, please?
https://stackoverflow.com/questions/70767805/error-building-the-downstream-libh3-c-library-using-the-solana-sdk-via-cmake/70772819?noredirect=1#comment125227594_70772819

https://stackoverflow.com/questions/70832630/cmake-error-when-building-a-c-library-as-bpf

**Comment by mvines** [comment]
Hi @johhnsmmith198, I don't provide general Solana support in this project. Try the Solana #developer-support channel at https://discord.gg/XPyr3GJs instead
