### ISSUE TITLE
error: no such subcommand: `build-bpf`

### ISSUE THREAD

**Issue by GildedHonour** [mvines/solana-bpf-program-template#8]
"cargo build" works, whereas

```
$ cargo build-bpf 
error: no such subcommand: `build-bpf`

```
And

```
rustc --print sysroot
/home/me123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
```

**Comment by mvines** [comment]
Try following step 2 of https://github.com/mvines/solana-bpf-program-template#environment-setup

**Comment by GildedHonour** [comment]
That's what I've done

**Comment by mvines** [comment]
What does `which cargo-build-bpf ` output for you?

Here's mine:
```
$ which cargo-build-bpf 
/Users/mvines/.local/share/solana/install/active_release/bin/cargo-build-bpf
```

**Comment by GildedHonour** [comment]
cargo-build-bpf not found

**Comment by mvines** [comment]
Ok you have some kind of a path issue.  That program is distributed with the Solana tools, and will be in the same directory as the `solana` program

**Comment by GildedHonour** [comment]
strange

```
% sudo find /~ -iname "*cargo-build-bpf*" 
% sudo find /usr -iname "*cargo-build-bpf*" 
% sudo find /var -iname "*cargo-build-bpf*" 
% sudo find /opt -iname "*cargo-build-bpf*" 
```

**Comment by crispycret** [comment]
Same issue as GildedHonour.

I built solana from source because my cpu is not compatible with any builds. I have removed and rebuilt solana a few times now with the same error persisting. I have also removed and re-installed rust and cargo a few times to no avail. 

Before I posted I wanted to try connecting the path AGAIN using the method from the solana build suite and that worked. Although I don't think it will persist but if I have to connect the path once in a while that's not so bad.

navigate to your solana folder and run `export PATH=$PWD/bin:$PATH` then navigate back to the `solana-bpf-template` example project and run cargo build-bpf. This worked for me/

**Comment by saibaneer** [comment]
I've encountered this error. In my case, when i run ```solana --version``` my distribution reports ```solana: command not found```. If this is your case, the run this to fix the path error: ```export PATH="$PATH:$HOME/.local/share/solana/install/active_release/bin/"```. 

Once you have done this, try and run ```anchor build``` again, it should work this time.

**Comment by saibaneer** [comment]
> "cargo build" works, whereas
> 
> ```
> $ cargo build-bpf 
> error: no such subcommand: `build-bpf`
> ```
> 
> And
> 
> ```
> rustc --print sysroot
> /home/me123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
> ```


I've encountered this error. In my case, when i run solana --version my distribution reports solana: command not found. If this is your case, the run this to fix the path error: export PATH="$PATH:$HOME/.local/share/solana/install/active_release/bin/".

Once you have done this, try and run anchor build again, it should work this time.

**Comment by saibaneer** [comment]
> "cargo build" works, whereas
> 
> ```
> $ cargo build-bpf 
> error: no such subcommand: `build-bpf`
> ```
> 
> And
> 
> ```
> rustc --print sysroot
> /home/me123/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
> ```

I've encountered this error. In my case, when i run ```solana --version``` my distribution reports ```solana: command not found.``` If this is your case, the run this to fix the path error: ```export PATH="$PATH:$HOME/.local/share/solana/install/active_release/bin/"```.

Once you have done this, try and run ```anchor build``` again, it should work this time.
