### ISSUE TITLE
Error testing program

### ISSUE THREAD

**Issue by kLvin** [mvines/solana-bpf-program-template#9]
I am trying to test the template, but when I launch "cargo test" I found this message ...

**Any idea?**

`Caused by:
  process didn't exit successfully: `C:\Projects\Solana\solana-bpf-program-template\target\debug\build\openssl-sys-59fcca739d7b29a3\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  note: vcpkg did not find openssl: Could not look up details of packages in vcpkg tree could not read status file updates dir: El sistema no puede encontrar la ruta especificada. (os error 3)

  --- stderr
  thread 'main' panicked at '
`

**Comment by mvines** [comment]
We don't support windows currently
